spring:
  application:
    name: libraryapi
  datasource:
    url: jdbc:postgresql://localhost:5432/java_course
    username: java_user
    password: pass321
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
